services:
    ffmpeg:
        image: ffmpeg-${NAME}
        container_name: ffmpeg
        cpuset: ${ISOLATE_CPU}
        build:
            context: '${PWD}/workloads/ffmpeg'
            dockerfile: '$PWD/workloads/ffmpeg/${FILE}'
            args:
                - BASE=${IMAGE}
        volumes:
            - '${PWD}/workloads/ffmpeg/videos/:/videos'
        command: -i "videos/video1080p60fps.mp4"  -vcodec h264 -s 1280x720 -r 24 -acodec aac "video720p24fps.mp4"
