name: 'cypress-realworld-app'
description: 'A payment application to demonstrate real-world usage of Cypress testing methods, patterns, and workflows.'
development: false
cpus: 1
clients: 1
docker: true
images:
    - 'ubuntu:22.04'
    - 'debian:12.0'
    - 'alpine:3.18.2'
    - 'centos:8.4.2105'
