name: 'cypress-realworld-app'
description: 'A payment application to demonstrate real-world usage of Cypress testing methods, patterns, and workflows.'
development: false
cpus: 2
clients: 1
images:
    - 'ubuntu:latest'
    - 'debian:latest'
    - 'alpine:latest'
    - 'centos:latest'
