services:
    frontend:
        image: cypress-realworld-app-react
        container_name: cypress-realworld-app-react
        cpuset: ${BACKGROUND_CPU}
        ports:
            - '3000:3000'
        build:
            context: '${PWD}/cypress-realworld-app'
            dockerfile: '${PWD}/workloads/cypress-realworld-app/DockerfileReact'
        healthcheck:
            test: curl --head -X GET localhost:3000
            interval: 10s
            retries: 20
            start_period: 5s
            timeout: 10s
    client:
        image: cypress-realworld-app-cypress
        cpuset: ${BACKGROUND_CPU}
        build:
            context: '${PWD}/cypress-realworld-app'
            dockerfile: '${PWD}/workloads/cypress-realworld-app/DockerfileCypress'
        depends_on:
            frontend:
                condition: service_healthy
        network_mode: host
    backend:
        image: cypress-realworld-app-${NAME}
        container_name: cypress-realworld-app-${NAME}
        cpuset: ${ISOLATE_CPU}
        ports:
            - '3001:3001'
        build:
            context: '${PWD}/cypress-realworld-app'
            dockerfile: '${PWD}/workloads/cypress-realworld-app/${FILE}'
            args:
                - BASE=${IMAGE}
