name: 'base-docker'
description: 'Baseline workload with Docker containers'
development: false
cpus: 1
docker: true
images:
    - 'ubuntu:latest'
    - 'debian:latest'
    - 'alpine:latest'
    - 'centos:latest'
