name: 'base-docker'
description: 'Baseline workload with Docker containers'
development: false
cpus: 1
docker: true
images:
    - 'ubuntu:22.04'
    - 'debian:12.0'
    - 'alpine:3.18.2'
    - 'centos:8.4.2105'
