services:
    base-docker:
        image: base-docker-${NAME}
        container_name: base-docker
        cpuset: ${ISOLATE_CPU}
        build:
            context: '${PWD}/workloads/base-docker'
            dockerfile: '$PWD/workloads/base-docker/${FILE}'
            args:
                - BASE=${IMAGE}
                - TIME=120
