name: 'mattermost'
description: 'Mattermost is an open source platform for secure collaboration across the entire software development lifecycle'
development: false
cpus: 1
clients: 1
docker: true
images:
    - 'ubuntu:latest'
    - 'debian:latest'
    - 'alpine:latest'
    - 'centos:latest'
