services:
    db:
        # image: mysql:5.7
        image: mattermost-db
        container_name: mattermost-db
        cpuset: ${BACKGROUND_CPU}
        # build:
        #     context: .
        #     dockerfile: DockerfileMysql
        # environment:
        #     MYSQL_ROOT_PASSWORD: 'mostest'
        #     MYSQL_USER: 'mmuser'
        #     MYSQL_PASSWORD: 'mostest'
        #     MYSQL_DATABASE: 'mattermost_test'
        # ports:
        #     - '3306:3306'
        # expose:
        #     - '3306'
    mattermost:
        image: mattermost-${NAME}
        container_name: mattermost-${NAME}
        cpuset: ${ISOLATE_CPU}
        # build:
        #     context: .
        #     dockerfile: ${FILE}
        #     args:
        #         - BASE=${IMAGE}
        ports:
            - '8065:8065'
        extra_hosts:
            - 'dockerhost:127.0.0.1'
