name: 'redis-server'
description: 'Redis is an open source, in-memory data structure store, used as a database, cache, and message broker.'
development: false
cpus: 1
docker: true
images:
    - 'ubuntu:latest'
    - 'debian:latest'
    - 'alpine:latest'
    - 'centos:latest'
