name: 'nginx-vod-module-docker'
description: 'Docker NGINX-based MP4 Repackager'
development: false
cpus: 1
clients: 2
images:
    - 'ubuntu:latest'
    - 'debian:latest'
    - 'alpine:latest'
    - 'centos:latest'
