services:
    vod-module:
        image: nginx-vod-module-docker-${NAME}
        container_name: nginx-vod-module-docker-${NAME}
        cpuset: ${ISOLATE_CPU}
        build:
            context: '${PWD}/nginx-vod-module-docker'
            dockerfile: '$PWD/workloads/nginx-vod-module-docker/${FILE}'
            args:
                - BASE=${IMAGE}
        volumes:
            - '${PWD}/nginx-vod-module-docker/examples/videos:/opt/static/videos'
            - '${PWD}/workloads/nginx-vod-module-docker/nginx.conf:/usr/local/nginx/conf/nginx.conf'
        ports:
            - '3030:80'
    client:
        image: nginx-vod-module-docker-vlc
        cpuset: ${BACKGROUND_CPU}
        build:
            context: '${PWD}/nginx-vod-module-docker'
            dockerfile: '$PWD/workloads/nginx-vod-module-docker/Dockerfile.client'
        depends_on:
            - vod-module
